/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:2185f2ae-5678-4183-8e50-b393d2a619c0",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_tnF6gTDVn",
    "aws_user_pools_web_client_id": "188pgl92last2ad21mgemp8mkc",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "api2",
            "endpoint": "https://rjltnrrupg.execute-api.eu-west-3.amazonaws.com/dev",
            "region": "eu-west-3"
        }
    ],
    "aws_user_files_s3_bucket": "s3tripimages203834-dev",
    "aws_user_files_s3_bucket_region": "eu-west-3",
    "aws_dynamodb_all_tables_region": "eu-west-3",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamocomments-dev",
            "region": "eu-west-3"
        }
    ]
};


export default awsmobile;
